# Tell Travis this is a Java project
language: java

# Tell Travis we want container-based builds.
sudo: false

# Use the gradle wrapper for 2.7 instead of default 2.2
before_install:
  - chmod +x gradlew

# Prepare the workspace.
install:
  - ./gradlew setupCIWorkspace -S

# Build the Project.
script:
  - ./gradlew build -S
  # What does this do?
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

# Push success to CurseForge for release.
after_success:
  - ./gradlew curse -S

# Clean up after Gradle
env:
  global:
    TERM=dumb

# Cache libs, as to improve speed.
cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches
